workflows:
  android-release:
    name: Build Android Release APK
    max_build_duration: 60
    environment:
      groups:
        - firebase
        - signing
      vars:
        GRADLE_TASK: assembleRelease
        KEYSTORE_PATH: keystore.jks
    scripts:
      - echo "🔓 Decodificando keystore..."
      - echo $KEYSTORE_BASE64 | base64 --decode > app/$KEYSTORE_PATH
      
      - echo "🔓 Decodificando google-services.json..."
      - mkdir -p app
      - echo $GOOGLE_SERVICES_JSON | base64 --decode > app/google-services.json

      - echo "🛠️ Listando archivos en app para verificar keystore..."
      - ls -l app/

      - echo "🛠️ Otorgando permisos..."
      - chmod +x ./gradlew

      - echo "🚀 Iniciando compilación..."
      - |
        KEYSTORE_ABS_PATH="$(pwd)/app/$KEYSTORE_PATH"
        echo "Usando keystore en ruta absoluta: $KEYSTORE_ABS_PATH"
        ./gradlew $GRADLE_TASK \
          -Pandroid.injected.signing.store.file=$KEYSTORE_ABS_PATH \
          -Pandroid.injected.signing.store.password=$KEYSTORE_PASSWORD \
          -Pandroid.injected.signing.key.alias=$KEY_ALIAS \
          -Pandroid.injected.signing.key.password=$KEY_PASSWORD

      - echo "✅ APK compilado, listando archivos..."
      - find app/build/outputs/apk/

    artifacts:
      - app/build/outputs/apk/release/app-release.apk