workflows:
  android-release:
    name: Build Android Release APK
    max_build_duration: 60
    environment:
      vars:
        GRADLE_TASK: assembleRelease
    scripts:
      - echo "Granting execute permission to gradlew"
      - chmod +x ./gradlew
      - echo "Starting Gradle build..."
      - ./gradlew $GRADLE_TASK
      - echo "Listing APK files:"
      - find app/build/outputs/apk/
    artifacts:
    - app/build/outputs/apk/release/app-release-unsigned.apk

